### ISSUE TITLE
Rules/Before-doing-the-task

### ISSUE THREAD

**Issue by TheHienDuong** [Agility-Internship/Duong-The-Hien-HTML-CSS#24]
- [ ] Check the task in topic [TODO ](https://trello.com/b/88B4V79C/html-css-practice-01)
- [ ] Drag to the topic[ Doing](https://trello.com/b/88B4V79C/html-css-practice-01/Doing) to perform the task
- [ ] Pull code from the "main-working-branch"
- [ ] git checkout -b "Action/description-in-short" 
- [ ] git commit and push "Task-branch" in github

**Comment by phattruong-agilityio** [comment]
We don't have `master` branch

**Comment by phattruong-agilityio** [comment]
I don't see the task is doing
